# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
  
      - name: 'Install the dev version of the extension'
        run: |
          az extension add --source https://rolloutvalidationcli.blob.core.windows.net/cli/k8s_configuration-1.6.0-py3-none-any.whl -y
      - name: 'Run the deployment validation against the branch and commit'
        run: |
          az k8s-configuration flux cross-cluster rollout -u https://github.com/jonathan-innis/open-id-connect-action.git --branch main --commit $GITHUB_SHA
